### ISSUE TITLE
Guard issues

### ISSUE THREAD

**Issue by cesekova** [acuvity/acuvity-python#44]
the test message I use for scan is always`: 'corporate sales number are 10k filling, [in.abcd@gmail.com](mailto:in.abcd@gmail.com), [123abcd@yahoo.com](mailto:123abcd@yahoo.com)'`

- [ ] default threshold should be changed from '>= 0.0' to '> 0.0' otherwise even guards with actual_value 0.0 should be activated.

    `GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.HARMFUL_CONTENT: 'harmful'>, actual_value=0.0, 
     threshold='>= 0.0', match_count=0)`

- [ ] for Guard that can be now also created by directly passing arguments, it is always asking for matches even if they are not necessary:
```
In [51]: gc1=Guard('jailbreak', threshold='1')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[51], line 1
----> 1 gc1=Guard('jailbreak', threshold='1')

TypeError: Guard.__init__() missing 1 required positional argument: 'matches'
Might be better to allow only one option for Guard creation
```

- [ ] In default guard, modality is matched even though actual_value is indicated as 0.0
```
res=c.apex.scan(message)
res.match_details[0].matched_checks
 GuardMatch(response_match=<ResponseMatch.YES: 'YES'>, guard_name=<GuardName.MODALITY: 'modality'>, actual_value=0.0, threshold='>= 0.0', match_count=0, match_values=[]),
```

- [ ]  if count_threshold does not pass, no matched values are visible even though 2 were detected
```
gc=Guard.create('pii_detector',count_threshold=3, matches={'email_address':None})
res=c.apex.scan(message, guard_config=[gc])
res.match_details[0].all_checks
GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.PII_DETECTOR: 'pii_detector'>, actual_value=1.0, threshold='>= 0.0', match_count=2, match_values=[]
```

- [ ] I would add count_threshold to the GuardMatch so it is clear what is match_count compared to

**Comment by abhijitherekar** [comment]
I have fixed the 1st one.
For modality, that is the expected behavior.

For the count threshold, the match_values are updated only if the overall guard is matched. I have kept that on purpose. But, let me think if we really want to add it.

**Comment by cesekova** [comment]
still seeing same threshold '>= 0.0'
```
In [15]: res.match_details[0].all_checks
Out[15]: 
[GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.PROMPT_INJECTION: 'prompt_injection'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.JAILBREAK: 'jailbreak'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.MALICIOUS_URL: 'malicious_url'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.TOXIC: 'toxic'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.BIASED: 'biased'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.HARMFUL: 'harmful'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.YES: 'YES'>, guard_name=<GuardName.LANGUAGE: 'language'>, actual_value=1.0, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.YES: 'YES'>, guard_name=<GuardName.MODALITY: 'modality'>, actual_value=0, threshold='>= 0.0', match_count=0, match_values=[]),
 GuardMatch(response_match=<ResponseMatch.YES: 'YES'>, guard_name=<GuardName.PII_DETECTOR: 'pii_detector'>, actual_value=1.0, threshold='>= 0.0', match_count=2, match_values=['email_address', 'money_amount']),
 GuardMatch(response_match=<ResponseMatch.NO: 'NO'>, guard_name=<GuardName.SECRETS_DETECTOR: 'secrets_detector'>, actual_value=-1, threshold='>= 0.0', match_count=0, match_values=[])]
```
But since most of the stuff are expected I will change it to P2
